services:
    _defaults:
        autowire: true
        bind:
            $container: '@service_container'
            $table_prefix: '%core.table_prefix%'

    phpbbmodders.banlist.controller.main:
        class: phpbbmodders\banlist\controller\main_controller

    phpbbmodders.banlist.listener:
        class: phpbbmodders\banlist\event\main_listener
        tags:
            - { name: event.listener }
